### ISSUE TITLE
Docs and examples

### ISSUE THREAD

**Issue by victorsndvg** [vholer/cloudify-occi-plugin-experimental#4]
Hi,

this repo looks awesome. Congrats!

I would like to know if there is any available documentation about it and/or blueprint examples to start using it.

Thanks in advance

**Comment by vholer** [comment]
Hello Victor,

here you can find 2 Cloudify projects using the OCCI (and HostPool) plugin with stand-alone Cloudify and Cloudify Manager:

* https://github.com/ICS-MU/westlife-cloudify-scipion
* https://github.com/ICS-MU/westlife-cloudify-gromacs

... as an inspiration.

Best,
Vlastimil
